spring.application.name=Proyecto_GestionaStock

spring.datasource.url=jdbc:mysql://localhost:3306/db_inventario?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true